---
micronaut:
  application:
    name: MicronautGroovy
  server:
    port: 8089
  views:
    thymeleaf:
      enabled: true
      character-encoding: "UTF-8"
---
hibernate:
  hbm2ddl:
    auto: create-drop
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
dataSource:
  url: jdbc:h2:file:~/MicronautGroovy;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
